export const dummy = {
  dates: {
    maximum: "2023-11-15",
    minimum: "2023-10-04",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
      genre_ids: [27, 9648],
      id: 507089,
      original_language: "en",
      original_title: "Five Nights at Freddy's",
      overview:
        "80년대에 아이들이 실종되고 폐업한지 오래된 프레디의 피자가게 그곳의 야간 경비 알바를 하게 된 ‘마이크'는 캄캄한 어둠만이 존재하는 줄 알았던 피자가게에서 살아 움직이는 피자가게 마스코트 '프레디와 친구들’을 목격한다. 어딘가 기괴하고 섬뜩한 프레디와 친구들이 실체를 드러내기 시작하는데...",
      popularity: 2613.406,
      poster_path: "/h3hhfWdBhdb2JLMZprQ1IvBe90h.jpg",
      release_date: "2023-11-15",
      title: "프레디의 피자가게",
      video: false,
      vote_average: 8.093,
      vote_count: 1984,
    },
    {
      adult: false,
      backdrop_path: "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
      genre_ids: [28, 12, 878],
      id: 609681,
      original_language: "en",
      original_title: "The Marvels",
      overview:
        "강력한 힘으로 은하계를 수호하는 최강 히어로 캡틴 마블 캐럴 댄버스. 캡틴 마블의 오랜 친구의 딸이자, 빛의 파장을 조작하는 히어로 모니카 램보. 최애 히어로 캡틴 마블의 열렬한 팬인 미즈 마블 카말라 칸. 캡틴 마블에 대한 복수를 꿈꾸는 냉혹한 크리족 리더 다르-벤의 영향으로 세 명의 히어로는 능력을 사용할 때마다 서로의 위치가 뒤바뀌게 된다. 뜻하지 않게 우주와 지구를 넘나들게 되는 예측 불가하고 통제 불가한 상황 속, 다르-벤은 지구를 포함해 캡틴 마블이 고향이라고 부르는 수많은 행성을 모두 파멸시키려 하고, 이를 저지하기 위해 모인 팀 마블스는 하나로 힘을 모으는데…",
      popularity: 1222.618,
      poster_path: "/oPcZLwtrHIGHRvLoBbNBc2KppEU.jpg",
      release_date: "2023-11-08",
      title: "더 마블스",
      video: false,
      vote_average: 6.41,
      vote_count: 228,
    },
    {
      adult: false,
      backdrop_path: "/wl4NWiZwpzZH67HiDgpDImLyds9.jpg",
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: "en",
      original_title: "Expend4bles",
      overview:
        "테러 단체에게 핵미사일이 탈취되어 3차 세계대전이 발발할 위기의 상황에 ‘리’(제이슨 스타뎀)를 새로운 리더로 맞은 무적의 팀 익스펜더블이 작전에 투입되는데...",
      popularity: 1491.721,
      poster_path: "/dWR8OTRCcYDbBmd8GKsyJT73kU2.jpg",
      release_date: "2023-10-18",
      title: "익스펜더블 4",
      video: false,
      vote_average: 6.486,
      vote_count: 651,
    },
    {
      adult: false,
      backdrop_path: "/zgQQF04u3OgNBJqClRNby1FPz9s.jpg",
      genre_ids: [16, 10751, 28, 878],
      id: 893723,
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "신비한 힘을 가진 유성이 어드벤처 시티에 떨어진 날, 퍼피 구조대는 유성에서 나온 크리스탈 덕분에 초능력을 가진 ‘퍼피 히어로즈’로 변신한다. 하지만 악당 ‘험딩어 시장’과 미치광이 과학자 ‘빅토리아’는 초능력의 원천인 크리스탈을 빼앗아 어드벤처 시티를 지배하려 하는데..! 작고 약하게 태어났지만 오랫동안 큰 꿈을 키워 온 ‘스카이’와 퍼피 히어로즈는 주니어 구조대원들과 함께 어드벤처 시티를 지켜낼 수 있을까?",
      popularity: 738.418,
      poster_path: "/62CEuwp287mbVarn3f2KcSAsrj1.jpg",
      release_date: "2023-10-06",
      title: "퍼피 구조대: 더 마이티 무비",
      video: false,
      vote_average: 7.045,
      vote_count: 144,
    },
    {
      adult: false,
      backdrop_path: "/azD31DjpV3PJfjF3h72LVw2WCSD.jpg",
      genre_ids: [27],
      id: 807172,
      original_language: "en",
      original_title: "The Exorcist: Believer",
      overview:
        "한날한시에 동시에 사라졌던 앤젤라와 캐서린.  기억이 전부 사라진 채 상처투성이 몸으로 돌아온 두 아이는  이상증세를 보이며 날이 갈수록 섬뜩하게 변해간다. 마침내 두 아이의 몸을 동시에 차지한 악마가 존재를 드러내고, 한 명을 살리면 한 명이 죽는다는 충격적인 사실이 밝혀지는데…",
      popularity: 680.302,
      poster_path: "/gekQTgjZkPhpglvP1ZdTHBwi7xO.jpg",
      release_date: "2023-10-18",
      title: "엑소시스트: 믿는 자",
      video: false,
      vote_average: 6.18,
      vote_count: 524,
    },
    {
      adult: false,
      backdrop_path: "/lyHmhoRj3zXSdeCYbs2oOXLCF4K.jpg",
      genre_ids: [16, 12, 10751, 14],
      id: 459003,
      original_language: "uk",
      original_title: "Мавка: Лісова пісня",
      overview:
        "오랜 전쟁의 끝, 서로의 문을 닫아 버린 마법의 숲과 인간 세상. 숲의 정령이자 대자연의 새로운 수호자, 마브카는 어느 날 순수한 마음을 지닌 인간 청년 루카스와 사랑에 빠진다. 하지만 악당 킬리나는 사랑에 빠진 마브카의 마음을 이용해 숲을 파괴하고 숲의 심장을 차지하려는 음모를 꾸미는데…",
      popularity: 574.917,
      poster_path: "/3I9xCIGaT3xVINYSxjHrlqv0XWQ.jpg",
      release_date: "2023-10-18",
      title: "마브카 : 숲의 노래",
      video: false,
      vote_average: 7.3,
      vote_count: 481,
    },
    {
      adult: false,
      backdrop_path: "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
      genre_ids: [27, 53],
      id: 1008042,
      original_language: "en",
      original_title: "Talk to Me",
      overview:
        "실시간트렌드 #90초빙의챌린지 #넘사벽스릴 #주작아님  STEP 1. 촛불을 켜고 저승의 문을 연다.  STEP 2. 몸을 묶고 ‘죽은 자의 손’을 잡는다.  STEP 3. “내게 말해”라고 속삭인다.  STEP 4. 나타난 귀신에게 “널 들여보낸다”라고 말하면 빙의 완료.  ※ 경고 ※ 단, 90초 안에 깨울 것. 반드시 촛불을 꺼 문을 닫을 것. SNS에서 핫한 빙의 챌린지에 중독된 '미아'와 친구들. 위험한 게임을 이어가던 중 친구 '라일리'가 '미아'의 죽은 엄마에게 빙의되자 '미아'는 이성을 잃고 마의 90초를 넘기고 마는데! 죽음보다 끔찍하게, 당신을 무자비하게 뒤흔들 공포가 시작된다! #ㅌㅌㅁ #ㄷㄷㄷ",
      popularity: 451.145,
      poster_path: "/bYxNkZpRAygeo1Kbo79KJOn2Qjr.jpg",
      release_date: "2023-11-01",
      title: "톡 투 미",
      video: false,
      vote_average: 7.194,
      vote_count: 1711,
    },
    {
      adult: false,
      backdrop_path: "/mPayGWnbFwlqtE65HjqNDfFGb8I.jpg",
      genre_ids: [80, 18, 36],
      id: 466420,
      original_language: "en",
      original_title: "Killers of the Flower Moon",
      overview:
        "1920년대 오클라호마주 오세이지 부족 땅에서 석유가 발견된 후, 부족 사람들이 한 명씩 죽어 나가자 FBI가 미스터리를 풀기 위해 나선다.",
      popularity: 274.216,
      poster_path: "/6jByCqeQXEu3RR5qvlTCBamJQED.jpg",
      release_date: "2023-10-19",
      title: "플라워 킬링 문",
      video: false,
      vote_average: 7.777,
      vote_count: 856,
    },
    {
      adult: false,
      backdrop_path: "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
      genre_ids: [28, 12, 878],
      id: 695721,
      original_language: "en",
      original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
      overview:
        "반란의 불씨를 잠재우기 위해 시작된 잔인한 서바이벌 헝거게임. 헝거게임 10회를 맞아 ‘멘토제’가 도입되고 ‘스노우’는 12구역의 소녀 ‘루시 그레이’의 멘토가 된다. 그는 몰락한 가문의 영광을 되찾기 위해 ‘루시 그레이’를 헝거게임에서 우승 시키려 수단과 방법을 가리지 않는데…",
      popularity: 177.935,
      poster_path: "/9f9YsmXoy9ghqZKIVuKHkmGGZCY.jpg",
      release_date: "2023-11-15",
      title: "헝거게임: 노래하는 새와 뱀의 발라드",
      video: false,
      vote_average: 7.2,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/nKOutYdpjpxdeftoXcDnSAaD2z8.jpg",
      genre_ids: [53, 27, 9648],
      id: 954388,
      original_language: "en",
      original_title: "Arenas Mortales",
      overview:
        "컨퍼런스 참석을 위해 콜롬비아에 도착한 이혼 위기의 부부 ‘소피아’ & ‘조쉬’는 컨퍼런스 시작 전 막간을 이용해 초아치 숲으로 하이킹을 떠나지만 이내 곧 폭풍을 만난다. 설상가상으로 갑작스러운 강도를 만나 미지의 위험이 도사리는 열대 우림 ‘라스 아레나스’로 들어가게되고, 폭풍우 때문에 질퍽해진 토양으로 인해 살아서는 결코 탈출할 수 없는 진흙 구덩이 ‘퀵샌드’에 빠지고 마는데…",
      popularity: 172.358,
      poster_path: "/nGThQiFyH30IE3FV0DDwIiA3bv6.jpg",
      release_date: "2023-11-01",
      title: "퀵샌드",
      video: false,
      vote_average: 6.649,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/A1EWX46DxpEuiha7K0XY6vhWbdZ.jpg",
      genre_ids: [16, 12, 28, 14],
      id: 900667,
      original_language: "ja",
      original_title: "ONE PIECE FILM RED",
      overview:
        "오직 목소리 하나로 전 세계를 사로잡은 디바 ‘우타’.  그녀가 모습을 드러내는 첫 라이브 콘서트가 음악의 섬 ‘엘레지아’에서 열리고  ‘루피’가 이끄는 밀짚모자 해적단과 함께 수많은 ‘우타’ 팬들로 공연장은 가득 찬다.  그리고 이 콘서트를 둘러싼 해적들과 해군들의 수상한 움직임이 시작되는데…  드디어 전세계가 애타게 기다리던 ‘우타’의 등장과 함께 노래가 울려 퍼지고,  그녀가 ‘샹크스의 딸’이라는 충격적인 사실이 드러난다.  ‘루피’, ‘우타’, ‘샹크스’, 세 사람의 과거가 그녀의 노랫소리와 함께 밝혀진다! 여기에서",
      popularity: 178.32,
      poster_path: "/q9Ul66mQDGpAvqUrTZdSMSzym5w.jpg",
      release_date: "2022-11-30",
      title: "원피스 필름 레드",
      video: false,
      vote_average: 7.344,
      vote_count: 769,
    },
    {
      adult: false,
      backdrop_path: "/mRmRE4RknbL7qKALWQDz64hWKPa.jpg",
      genre_ids: [80, 53],
      id: 800158,
      original_language: "en",
      original_title: "The Killer",
      overview:
        "결정적 순간에 아슬아슬하게 타깃을 놓친 암살자. 사적인 감정은 없다면서도, 이 응징을 위해 국제적인 추격전에 뛰어든다. 그 여정에서 의뢰인들, 그리고 그 자신과의 싸움이 시작된다.",
      popularity: 192.682,
      poster_path: "/8yX4Bt1qTUETuVyWgqyqlFM1nzw.jpg",
      release_date: "2023-10-25",
      title: "더 킬러",
      video: false,
      vote_average: 7.019,
      vote_count: 265,
    },
    {
      adult: false,
      backdrop_path: "/pBdQ4iorzRV2G38mdS6rzrmUfMA.jpg",
      genre_ids: [28, 10752],
      id: 840326,
      original_language: "fi",
      original_title: "Sisu",
      overview:
        "라플란드의 황야 깊은 곳에서 금을 찾던 아타미 코피는 나치 순찰대를 우연히 만나게 되고, 파괴되고 채굴된 라플란드 황야를 가로지르는 숨막히는 추격전이 시작된다.",
      popularity: 155.26,
      poster_path: "/xnrs7mEfnDwW7EbMJ1YJrQQXf4E.jpg",
      release_date: "2023-10-25",
      title: "시수",
      video: false,
      vote_average: 7.537,
      vote_count: 1451,
    },
    {
      adult: false,
      backdrop_path: "/x9tsSyltV2N814LtABb41NjVMd7.jpg",
      genre_ids: [10402],
      id: 1160164,
      original_language: "en",
      original_title: "TAYLOR SWIFT | THE ERAS TOUR",
      overview:
        "이 문화적 현상이 대형 스크린에서 계속됩니다! 역사에 남을 숨 막히는 장면을 영화처럼 감상하며 일생일대의 콘서트 영화 체험에 푹 빠져보세요",
      popularity: 90.238,
      poster_path: "/pm6cudRCaKofVRDQBTgl5kzejK1.jpg",
      release_date: "2023-11-03",
      title: "테일러 스위프트: 디 에라스 투어",
      video: false,
      vote_average: 8.2,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      genre_ids: [16, 12, 14, 18],
      id: 508883,
      original_language: "ja",
      original_title: "君たちはどう生きるか",
      overview:
        "화재로 어머니를 잃은 11살 소년 ‘마히토’는 아버지와 함께 어머니의 고향으로 간다. 어머니에 대한 그리움과 새로운 보금자리에 적응하느라 힘들어하던 ‘마히토’ 앞에 정체를 알 수 없는 왜가리 한 마리가 나타나고, 저택에서 일하는 일곱 할멈으로부터 왜가리가 살고 있는 탑에 대한 신비로운 이야기를 듣게 된다. 그러던 어느 날, ‘마히토’는 사라져버린 새엄마 ‘나츠코’를 찾기 위해 탑으로 들어가고, 왜가리가 안내하는 대로 이세계(異世界)의 문을 통과하는데…!",
      popularity: 90.766,
      poster_path: "/kmoScy628A6JWv8mmd2ofrYv16T.jpg",
      release_date: "2023-10-25",
      title: "그대들은 어떻게 살 것인가",
      video: false,
      vote_average: 7.3,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: "/jbFFcfNdjs4Sxvxzp2lWkyB0hLO.jpg",
      genre_ids: [18],
      id: 1075813,
      original_language: "zh",
      original_title: "绿夜",
      overview:
        "인천 여객항 보안검색대에서 근무하는 이방인 진샤. 낯선 타지에서 쳇바퀴 같은 삶을 살아가던 그녀 앞에 자신과 달리 자유로워 보이는 초록머리 여자가 나타난다. 운명처럼 이끌리게 된 진샤와 초록머리 여자는 이내 돌이킬 수 없는 사건에 휘말리게 되고, 두 사람은 예측하기 어려운 긴 밤을 마주하는데…",
      popularity: 72.787,
      poster_path: "/yRVhskwWg2WyQMEMGB3oZQqTqPZ.jpg",
      release_date: "2023-11-01",
      title: "녹야",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/gknIloEJve4FgAzlKdOUZu1K9HT.jpg",
      genre_ids: [53],
      id: 1109534,
      original_language: "en",
      original_title: "The Dive",
      overview:
        "외딴섬으로 다이빙을 떠난 자매 ‘드류’와 ‘메이’ 아름다운 바다 풍경에 감탄하던 것도 잠시, 산사태로 인해 거대한 바위와 물속으로 굴러떨어지고 바위는 두 사람을 깊은 바다 수면 속으로 끌고 들어간다. 수심 28m 추락, 생존 제한 시간 단 20분. 깊어질수록 턱 끝까지 차오르는 압도적 공포!",
      popularity: 52.645,
      poster_path: "/gzqSFsFOIsEYFZxMVdgwZGyEGKT.jpg",
      release_date: "2023-11-08",
      title: "다이브: 100 피트 추락",
      video: false,
      vote_average: 6.094,
      vote_count: 53,
    },
    {
      adult: false,
      backdrop_path: "/2Eewgp7o5AU1xCataDmiIL2nYxd.jpg",
      genre_ids: [36, 18],
      id: 943822,
      original_language: "en",
      original_title: "Prizefighter: The Life of Jem Belcher",
      overview:
        "복싱 역사를 새로 쓴 전설의 복싱 스타 ‘젬 벨처’, 마지막이 될지도 모르는 위대한 경기를 시작한다!",
      popularity: 53.346,
      poster_path: "/j4qMuoEieZrb4LFZLQ918BkzCyG.jpg",
      release_date: "2023-11-15",
      title: "더 챔피언",
      video: false,
      vote_average: 6.4,
      vote_count: 156,
    },
    {
      adult: false,
      backdrop_path: "/bmStpqOfwZt7tUbGZXp3VbSL8a0.jpg",
      genre_ids: [878, 53],
      id: 942199,
      original_language: "en",
      original_title: "Simulant",
      overview:
        "AI는 인간과 공존하기 위해 네 가지 원칙을 반드시 준수한다. ‘첫째, 인간을 절대 해치지 않는다’ ‘둘째, 스스로 프로그램을 수정하거나 복제할 수 없다’ ‘셋째, 법을 위반하지 않는다’ ‘넷째, 주인의 명령에 무조건 복종한다’ 그러나 의문의 해킹을 통해 인간의 통제를 벗어나 스스로 사고하게 된 AI들의 이탈이 이어지고, 그들을 쫓는 특수요원, 그리고 비밀의 키를 쥔 해커의 쫓고 쫓기는 추격전이 시작된다.",
      popularity: 37.538,
      poster_path: "/l2vYulanIYHpwJud1cxn0aot5mI.jpg",
      release_date: "2023-11-02",
      title: "시뮬런트",
      video: false,
      vote_average: 5.909,
      vote_count: 115,
    },
    {
      adult: false,
      backdrop_path: "/cyV2syN5zRQwU6BmWMyMFyjRLow.jpg",
      genre_ids: [28, 80, 53],
      id: 843633,
      original_language: "en",
      original_title: "White Elephant",
      overview:
        "단 한 번의 실패 없이 생애 모든 미션을 성공한 킬러 ‘게이브’(마이클 루커) 사랑하는 아내의 죽음 이후 그녀와의 약속을 지키기 위해 은퇴를 결심하던 그에게 부동산 재벌이자 절친한 친구 ‘아놀드’(브루스 윌리스)는 마지막 의뢰를 지시한다. 그러나 이를 완수하고 후계자 ‘카를로’와 함께 복귀하던 중 잠복한 형사들을 마주하게 되고, 목격자가 된 이들을 제거하기 위한 사투를 벌인다. 한편, 격전의 전투 속에서 ‘게이브’는 마지막 의뢰 속 숨겨진 진실을 알게 되고, 뒤쫓던 여형사 ‘바네사’와 함께 역으로 조직을 말살하기 위한 작전을 펼치는데…",
      popularity: 22.74,
      poster_path: "/aljO2O1SP21GziM2Gc34jnSjac3.jpg",
      release_date: "2023-11-15",
      title: "브루스 윌리스의 라스트 미션: 데이 투 다이",
      video: false,
      vote_average: 6.158,
      vote_count: 130,
    },
  ],
  total_pages: 4,
  total_results: 80,
};
